-- Idempotent migrations for existing deployments

ALTER TABLE channels ADD COLUMN IF NOT EXISTS target_duration_minutes INTEGER NOT NULL DEFAULT 10;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS audience_level TEXT NOT NULL DEFAULT 'general';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS title_style TEXT NOT NULL DEFAULT 'curiosity';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS auto_publish BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS youtube_category_id TEXT NOT NULL DEFAULT '28';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS creatomate_thumbnail_template_id TEXT;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS require_thumbnail BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE videos ADD COLUMN IF NOT EXISTS ctr NUMERIC(8, 4) DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS avg_view_duration_seconds NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS impressions BIGINT DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS analytics_synced_at TIMESTAMPTZ;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS thumbnail_uploaded BOOLEAN DEFAULT FALSE;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS quality_score NUMERIC(5, 2);
ALTER TABLE videos ADD COLUMN IF NOT EXISTS quality_notes TEXT;
